# Generated by Django 2.0.5 on 2020-01-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chainview', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_link', models.CharField(blank=True, choices=[('income', 'Income'), ('chain', 'Chain'), ('loan', 'Loan'), (' ', '------')], default='income', max_length=10, null=True)),
                ('money_spent', models.PositiveIntegerField()),
                ('money_source', models.CharField(blank=True, choices=[('icici_cc', 'ICICI CC'), ('sbi_cc', 'SBI CC'), ('hdfc_cc', 'HDFC CC'), ('icici_dc', 'ICICI DC'), ('hdfc_dc', 'HDFC DC'), ('sbi_dc', 'SBI DC'), ('kvb', 'kvb'), ('h_c', 'Hand Cash')], default='sbi_cc', max_length=10, null=True)),
                ('expense_category', models.CharField(choices=[('food', 'food'), ('cloth', 'cloth'), ('petrol', 'petrol'), ('groceries', 'groceries'), ('veggies', 'veggies'), ('petrol', 'petrol'), ('entertainment', 'entertainment'), ('medical', 'medical'), ('fashion', 'fashion'), ('interest', 'interest'), ('bank_charges', 'Bank Charges'), ('phone_charges', 'Phone Charges'), ('home_internet', 'Home Internet'), ('travel', 'travel'), ('electric', 'Electrical'), ('cash_with', 'Cash Withdrawl'), ('loan_given', 'Hand Loan'), ('education', 'Education'), ('others', 'others')], default='groceries', max_length=20)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('purchase_date', models.DateField()),
                ('chain_link', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='expenditures.chain')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomes', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnslist', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraws', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='income_link',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='expenditures.income'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='loan_link',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='expenditures.loan'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='returns_link',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='expenditures.returns'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='withdraw_link',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='expenditures.withdraw'),
        ),
    ]
